// GENERATED by carrier.py -- edit that, not this.
//
// Two printed halves.  Each carries one array on a 1.5 mm aluminium plate,
// and they bolt to each other through the lap in the middle of the bar.
// Print both flat, opening upwards, no supports.
//
//   separation is set by which holes you line up in the lap:
//   370 to 430 mm in 10 mm steps.  400 is the design point.

part = "all";     // "transmit" | "receive" | "all"
$fn = 48;

module tray_tx() {
  difference() {
    union() {
      translate([-48.921, -37.195, 0])
        cube([97.000, 73.000, 7.70]);
    }
    // pocket the plate drops into
    translate([-46.071, -34.345, 5.00])
      cube([91.300, 67.300, 3.70]);
    // fasteners, each with an M3 nut trapped in the underside
      translate([-31.921, 8.805, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-31.921, 8.805, -1]) cylinder(d=3.40, h=8.00);
      translate([31.079, 5.805, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([31.079, 5.805, -1]) cylinder(d=3.40, h=8.00);
      translate([-1.921, -30.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-1.921, -30.195, -1]) cylinder(d=3.40, h=8.00);
      translate([7.079, -17.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([7.079, -17.195, -1]) cylinder(d=3.40, h=8.00);
      translate([-6.921, -17.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-6.921, -17.195, -1]) cylinder(d=3.40, h=8.00);
      translate([-40.921, -0.695, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-40.921, -0.695, -1]) cylinder(d=3.40, h=8.00);
      translate([40.250, -0.695, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([40.250, -0.695, -1]) cylinder(d=3.40, h=8.00);
      translate([-16.801, 22.923, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-16.801, 22.923, -1]) cylinder(d=3.40, h=8.00);
      translate([15.959, 22.923, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([15.959, 22.923, -1]) cylinder(d=3.40, h=8.00);
  }
}

module tray_rx() {
  difference() {
    union() {
      translate([-37.195, -448.948, 0])
        cube([73.000, 97.000, 7.70]);
    }
    // pocket the plate drops into
    translate([-34.345, -446.098, 5.00])
      cube([67.300, 91.300, 3.70]);
    // fasteners, each with an M3 nut trapped in the underside
      translate([-30.195, -391.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-30.195, -391.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-27.195, -411.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-27.195, -411.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-17.195, -399.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-17.195, -399.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-0.695, -440.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-0.695, -440.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-0.695, -359.763, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-0.695, -359.763, -1]) cylinder(d=3.40, h=8.00);
      translate([22.923, -416.828, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([22.923, -416.828, -1]) cylinder(d=3.40, h=8.00);
      translate([22.923, -384.068, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([22.923, -384.068, -1]) cylinder(d=3.40, h=8.00);
  }
}

module arm_tx() {{
  difference() {{
    union() {{
      translate([-12.500, -171.571, 0])
        cube([12.500, 168.376, 12.00]);
      // local pad, deep enough to swallow a 1/4-20 tripod nut
      translate([-21.000, -83.571, 0])
        cube([8.50, 34.00, 12.00]);
    }}
    translate([-13.500, -161.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -151.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -141.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -131.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -121.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -111.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -101.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    // tripod thread, and two M4 for any flat bracket
    translate([-10.500, -66.571, -1])
      cylinder(d=6.80, h=14.00, $fn=32);
    translate([-10.500, -66.571, -0.01])
      cylinder(d=13.164, h=6.00, $fn=6);
    translate([-10.500, -77.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
    translate([-10.500, -55.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
  }}
}}

module arm_rx() {{
  difference() {{
    union() {{
      translate([0.000, -385.948, 0])
        cube([12.500, 144.376, 12.00]);
      // local pad, deep enough to swallow a 1/4-20 tripod nut
      translate([12.500, -363.571, 0])
        cube([8.50, 34.00, 12.00]);
    }}
    translate([-13.500, -251.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -261.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -271.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -281.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -291.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -301.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -311.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    // tripod thread, and two M4 for any flat bracket
    translate([10.500, -346.571, -1])
      cylinder(d=6.80, h=14.00, $fn=32);
    translate([10.500, -346.571, -0.01])
      cylinder(d=13.164, h=6.00, $fn=6);
    translate([10.500, -357.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
    translate([10.500, -335.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
  }}
}}

module half_tx() {
  difference() {
    union() {
      tray_tx();
      arm_tx();
    }
    // The arm reaches 34 mm back under its own tray, so the pocket has
    // to be cut a second time from the finished union.  It must also be cut
    // ALL the way up: the arm is 12 mm thick against the tray's
    // 7.7 mm, and a pocket only as deep as the plate left a
    // tongue of plastic hanging over the antenna's face, 1.4 mm off the
    // copper.  Nothing may stand in front of a patch.
    translate([-46.071, -34.345, 5.00])
      cube([91.300, 67.300, 17.00]);
    // clear runs for the coaxial connectors
    translate([-37.521, -48.195, -1]) cube([16.000, 25.000, 14.00]);
    translate([12.523, -48.195, -1]) cube([16.000, 25.000, 14.00]);
  }
}

module half_rx() {
  difference() {
    union() {
      tray_rx();
      arm_rx();
    }
    translate([-34.345, -446.098, 5.00])
      cube([67.300, 91.300, 17.00]);
    translate([-51.195, -437.521, -1]) cube([28.000, 16.000, 14.00]);
    translate([-51.195, -387.477, -1]) cube([28.000, 16.000, 14.00]);
  }
}


module cradle() {
  difference() {
    union() {
      cube([107.50, 165.50, 9.00]);
      // two tabs onto the spine's own mounting pad
      translate([39.75, 164.50, 0])
        cube([28.0, 16.0, 5.00]);
    }
    // the radio drops in from the front
    translate([5.00, 5.00, 5.00])
      cube([97.50, 155.50, 5.00]);
    // and most of the back is open, so it can breathe and lose weight
    translate([17.00, 17.00, -1])
      cube([73.00, 131.00, 7.00]);
    // four M4 onto the spine pad
    for (dx = [-8, 8], dy = [6, 19])
      translate([53.75 + dx, 165.50 + dy - 1, -1])
        cylinder(d=4.50, h=7.00, $fn=24);
  }
  // posts holding the outer edge of the front-end board
  for (p = [21.0, 79.0])
    translate([53.75 - 50.0 + 100.0 - 4.5, p + 5.00, 0])
      difference() {
        cylinder(d=9.0, h=15.00, $fn=32);
        translate([0, 0, 12.00])
          cylinder(d=7.159, h=3.80, $fn=6);
        translate([0, 0, -1]) cylinder(d=3.40, h=17.00);
      }
}

module extender() {
  difference() {
    union() {
      // the half-depth tongue that laps whatever is above it
      translate([0.00, -80.00, 0])
        cube([12.50, 80.00, 12.00]);
      // full depth through the middle
      translate([-12.50, -75.00, 0])
        cube([25.00, -5.00, 12.00]);
      // and the tongue that laps whatever is below, on the other side
      translate([-12.50, -155.00, 0])
        cube([12.50, 80.00, 12.00]);
    }
    translate([-13.50, -10.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -20.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -30.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -40.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -50.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -60.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -70.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -85.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -95.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -105.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -115.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -125.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -135.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.50, -145.00, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
  }
}

if (part == "cradle") cradle();
else if (part == "extender") extender();
else if (part == "transmit") half_tx();
else if (part == "receive") half_rx();
else {
  half_tx();
  half_rx();
  color("#7f8fa6") translate([0, -91.571, 0]) extender();
  color("#94a3b8") translate([0, -166.571, 0]) mirror([1,0,0]) extender();
  translate([-64.250, -239.071, -19.00])
    color("#4a6fa5") cradle();

  // the aluminium, and the boards sitting on it
  color("silver") translate([-45.921, -34.195, 5.00])
    cube([91.00, 67.00, 1.50]);
  color("silver") translate([-34.195, -445.948, 5.00])
    cube([67.00, 91.00, 1.50]);
  color("green") translate([-35.921, -34.195,
    6.50])
    cube([71.342, 47.237, 0.76]);
  color("green") translate([-34.195, -435.948,
    6.50])
    cube([47.237, 71.369, 0.76]);
}
