// GENERATED by carrier.py -- edit that, not this.
//
// Two printed halves.  Each carries one array on a 1.5 mm aluminium plate,
// and they bolt to each other through the lap in the middle of the bar.
// Print both flat, opening upwards, no supports.
//
//   separation is set by which holes you line up in the lap:
//   220 to 280 mm in 10 mm steps.  250 is the design point.

part = "all";     // "transmit" | "receive" | "all"
$fn = 48;

module tray_tx() {
  difference() {
    union() {
      translate([-48.921, -37.195, 0])
        cube([97.000, 73.000, 7.70]);
    }
    // pocket the plate drops into
    translate([-46.071, -34.345, 5.00])
      cube([91.300, 67.300, 3.70]);
    // fasteners, each with an M3 nut trapped in the underside
      translate([-31.921, 8.805, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-31.921, 8.805, -1]) cylinder(d=3.40, h=8.00);
      translate([31.079, 5.805, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([31.079, 5.805, -1]) cylinder(d=3.40, h=8.00);
      translate([-1.921, -30.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-1.921, -30.195, -1]) cylinder(d=3.40, h=8.00);
      translate([7.079, -17.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([7.079, -17.195, -1]) cylinder(d=3.40, h=8.00);
      translate([-6.921, -17.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-6.921, -17.195, -1]) cylinder(d=3.40, h=8.00);
      translate([-40.921, -0.695, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-40.921, -0.695, -1]) cylinder(d=3.40, h=8.00);
      translate([40.250, -0.695, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([40.250, -0.695, -1]) cylinder(d=3.40, h=8.00);
      translate([-16.801, 22.923, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-16.801, 22.923, -1]) cylinder(d=3.40, h=8.00);
      translate([15.959, 22.923, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([15.959, 22.923, -1]) cylinder(d=3.40, h=8.00);
  }
}

module tray_rx() {
  difference() {
    union() {
      translate([-37.195, -298.948, 0])
        cube([73.000, 97.000, 7.70]);
    }
    // pocket the plate drops into
    translate([-34.345, -296.098, 5.00])
      cube([67.300, 91.300, 3.70]);
    // fasteners, each with an M3 nut trapped in the underside
      translate([-30.195, -241.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-30.195, -241.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-26.195, -261.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-26.195, -261.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-17.195, -249.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-17.195, -249.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-0.695, -290.948, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-0.695, -290.948, -1]) cylinder(d=3.40, h=8.00);
      translate([-0.695, -209.763, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-0.695, -209.763, -1]) cylinder(d=3.40, h=8.00);
      translate([22.923, -266.828, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([22.923, -266.828, -1]) cylinder(d=3.40, h=8.00);
      translate([22.923, -234.068, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([22.923, -234.068, -1]) cylinder(d=3.40, h=8.00);
  }
}

module arm_tx() {{
  difference() {{
    union() {{
      translate([-12.500, -171.571, 0])
        cube([12.500, 168.376, 12.00]);
      // local pad, deep enough to swallow a 1/4-20 tripod nut
      translate([-21.000, -83.571, 0])
        cube([8.50, 34.00, 12.00]);
    }}
    translate([-13.500, -161.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -151.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -141.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -131.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -121.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -111.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -101.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    // tripod thread, and two M4 for any flat bracket
    translate([-10.500, -66.571, -1])
      cylinder(d=6.80, h=14.00, $fn=32);
    translate([-10.500, -66.571, -0.01])
      cylinder(d=13.164, h=6.00, $fn=6);
    translate([-10.500, -77.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
    translate([-10.500, -55.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
  }}
}}

module arm_rx() {{
  difference() {{
    union() {{
      translate([0.000, -235.948, 0])
        cube([12.500, 144.376, 12.00]);
      // local pad, deep enough to swallow a 1/4-20 tripod nut
      translate([12.500, -213.571, 0])
        cube([8.50, 34.00, 12.00]);
    }}
    translate([-13.500, -101.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -111.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -121.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -131.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -141.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -151.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([-13.500, -161.571, 6.00]) rotate([0,90,0]) cylinder(d=3.40, h=27.00, $fn=24);
    // tripod thread, and two M4 for any flat bracket
    translate([10.500, -196.571, -1])
      cylinder(d=6.80, h=14.00, $fn=32);
    translate([10.500, -196.571, -0.01])
      cylinder(d=13.164, h=6.00, $fn=6);
    translate([10.500, -207.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
    translate([10.500, -185.571, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
  }}
}}

module half_tx() {
  difference() {
    union() {
      tray_tx();
      arm_tx();
    }
    // the arm runs up into the tray, so cut the plate pocket again here or
    // it fills the corner of it
    translate([-46.071, -34.345, 5.00])
      cube([91.300, 67.300, 3.70]);
    // clear runs for the coaxial connectors
    translate([-37.521, -48.195, -1]) cube([16.000, 25.000, 14.00]);
    translate([12.523, -48.195, -1]) cube([16.000, 25.000, 14.00]);
  }
}

module half_rx() {
  difference() {
    union() {
      tray_rx();
      arm_rx();
    }
    translate([-34.345, -296.098, 5.00])
      cube([67.300, 91.300, 3.70]);
    translate([-51.195, -287.521, -1]) cube([28.000, 16.000, 14.00]);
    translate([-51.195, -237.477, -1]) cube([28.000, 16.000, 14.00]);
  }
}


module shelf_pa() {
  difference() {
    union() {
      cube([112.00, 96.00, 5.00]);
      translate([42.000, 95.000, 0])
        cube([28.0, 16.0, 5.00]);
    }
    translate([11.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([11.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([11.000, 85.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([11.000, 85.000, -1]) cylinder(d=3.40, h=7.00);
    translate([42.500, 28.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([42.500, 28.000, -1]) cylinder(d=3.40, h=7.00);
    translate([42.500, 68.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([42.500, 68.000, -1]) cylinder(d=3.40, h=7.00);
    translate([101.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([101.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([101.000, 85.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([101.000, 85.000, -1]) cylinder(d=3.40, h=7.00);
    translate([48.000, 96.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([48.000, 109.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([64.000, 96.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([64.000, 109.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    for (i = [0 : 2]) for (j = [0 : 1])
      translate([24.00 + i * 30, 26.00 + j * 30, -1])
        cube([18, 20, 7.00]);
  }
}

module shelf_lna() {
  difference() {
    union() {
      cube([104.00, 80.00, 5.00]);
      translate([38.000, 79.000, 0])
        cube([28.0, 16.0, 5.00]);
    }
    translate([11.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([11.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([11.000, 69.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([11.000, 69.000, -1]) cylinder(d=3.40, h=7.00);
    translate([42.500, 24.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([42.500, 24.000, -1]) cylinder(d=3.40, h=7.00);
    translate([42.500, 56.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([42.500, 56.000, -1]) cylinder(d=3.40, h=7.00);
    translate([93.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([93.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([93.000, 69.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([93.000, 69.000, -1]) cylinder(d=3.40, h=7.00);
    translate([44.000, 80.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([44.000, 93.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([60.000, 80.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([60.000, 93.500, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    for (i = [0 : 2]) for (j = [0 : 1])
      translate([24.00 + i * 30, 26.00 + j * 30, -1])
        cube([18, 20, 7.00]);
  }
}

if (part == "shelf_pa") shelf_pa();
else if (part == "shelf_lna") shelf_lna();
else if (part == "transmit") half_tx();
else if (part == "receive") half_rx();
else {
  half_tx();
  half_rx();
  translate([-66.500, -169.571, -5.00])
    color("#4a6fa5") shelf_pa();
  translate([-41.500, -283.571, -5.00])
    color("#4a6fa5") shelf_lna();

  // the aluminium, and the boards sitting on it
  color("silver") translate([-45.921, -34.195, 5.00])
    cube([91.00, 67.00, 1.50]);
  color("silver") translate([-34.195, -295.948, 5.00])
    cube([67.00, 91.00, 1.50]);
  color("green") translate([-35.921, -34.195,
    6.50])
    cube([71.342, 47.237, 0.76]);
  color("green") translate([-34.195, -285.948,
    6.50])
    cube([47.237, 71.369, 0.76]);
}
