// GENERATED by carrier.py -- edit that, not this.
//
// Two printed halves.  Each carries one array on a 1.5 mm aluminium plate,
// and they bolt to each other through the lap in the middle of the bar.
// Print both flat, opening upwards, no supports.
//
//   separation is set by which holes you line up in the lap:
//   220 to 280 mm in 10 mm steps.  250 is the design point.

part = "all";     // "transmit" | "receive" | "all"
$fn = 48;

module tray_tx() {
  difference() {
    union() {
      translate([-48.921, -37.195, 0])
        cube([97.000, 73.000, 7.70]);
    }
    // pocket the plate drops into
    translate([-46.071, -34.345, 5.00])
      cube([91.300, 67.300, 3.70]);
    // fasteners, each with an M3 nut trapped in the underside
      translate([10.079, -30.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([10.079, -30.195, -1]) cylinder(d=3.40, h=8.00);
      translate([-31.921, 8.805, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-31.921, 8.805, -1]) cylinder(d=3.40, h=8.00);
      translate([31.079, 8.805, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([31.079, 8.805, -1]) cylinder(d=3.40, h=8.00);
      translate([-11.921, -26.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-11.921, -26.195, -1]) cylinder(d=3.40, h=8.00);
      translate([0.079, -21.195, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([0.079, -21.195, -1]) cylinder(d=3.40, h=8.00);
      translate([-40.921, -0.695, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-40.921, -0.695, -1]) cylinder(d=3.40, h=8.00);
      translate([40.250, -0.695, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([40.250, -0.695, -1]) cylinder(d=3.40, h=8.00);
      translate([-16.801, 22.923, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([-16.801, 22.923, -1]) cylinder(d=3.40, h=8.00);
      translate([15.959, 22.923, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([15.959, 22.923, -1]) cylinder(d=3.40, h=8.00);
  }
}

module tray_rx() {
  difference() {
    union() {
      translate([212.805, -48.921, 0])
        cube([73.000, 97.000, 7.70]);
    }
    // pocket the plate drops into
    translate([215.655, -46.071, 5.00])
      cube([67.300, 91.300, 3.70]);
    // fasteners, each with an M3 nut trapped in the underside
      translate([219.805, 9.079, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([219.805, 9.079, -1]) cylinder(d=3.40, h=8.00);
      translate([258.805, -31.921, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([258.805, -31.921, -1]) cylinder(d=3.40, h=8.00);
      translate([258.805, 31.079, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([258.805, 31.079, -1]) cylinder(d=3.40, h=8.00);
      translate([223.805, -11.921, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([223.805, -11.921, -1]) cylinder(d=3.40, h=8.00);
      translate([228.805, 0.079, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([228.805, 0.079, -1]) cylinder(d=3.40, h=8.00);
      translate([249.305, -40.921, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([249.305, -40.921, -1]) cylinder(d=3.40, h=8.00);
      translate([249.305, 40.250, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([249.305, 40.250, -1]) cylinder(d=3.40, h=8.00);
      translate([272.923, -16.801, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([272.923, -16.801, -1]) cylinder(d=3.40, h=8.00);
      translate([272.923, 15.959, -1]) cylinder(d=7.159, h=3.80, $fn=6);
      translate([272.923, 15.959, -1]) cylinder(d=3.40, h=8.00);
  }
}

module arm_tx() {
  difference() {
    union() {
      translate([14.079, -63.421, 0])
        cube([144.363, 12.500, 12.00]);
      // local pad, deep enough to swallow a 1/4-20 tripod nut
      translate([36.442, -50.921, 0])
        cube([34.00, 8.50, 12.00]);
    }
    translate([148.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([138.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([128.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([118.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([108.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([98.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([88.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    // tripod thread, and two M4 for any flat bracket
    translate([53.442, -52.921, -1])
      cylinder(d=6.80, h=14.00, $fn=32);
    translate([53.442, -52.921, -0.01])
      cylinder(d=13.164, h=6.00, $fn=6);
    translate([42.442, -52.921, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
    translate([64.442, -52.921, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
  }
}

module arm_rx() {
  difference() {
    union() {
      translate([78.442, -75.921, 0])
        cube([168.363, 12.500, 12.00]);
      // local pad, deep enough to swallow a 1/4-20 tripod nut
      translate([166.442, -84.421, 0])
        cube([34.00, 8.50, 12.00]);
    }
    translate([88.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([98.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([108.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([118.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([128.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([138.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    translate([148.442, -76.921, 6.00]) rotate([-90,0,0]) cylinder(d=3.40, h=27.00, $fn=24);
    // tripod thread, and two M4 for any flat bracket
    translate([183.442, -73.921, -1])
      cylinder(d=6.80, h=14.00, $fn=32);
    translate([183.442, -73.921, -0.01])
      cylinder(d=13.164, h=6.00, $fn=6);
    translate([172.442, -73.921, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
    translate([194.442, -73.921, -1])
      cylinder(d=4.5, h=14.00, $fn=24);
  }
}

module half_tx() {
  difference() {
    union() {
      tray_tx();
      arm_tx();
    translate([14.079, -50.921, 0])
      cube([34.00, 13.726, 12.00]);
    }
    // clear runs for the coaxial connectors, through the gusset as well
    translate([-37.521, -50.921, -1]) cube([16.000, 27.726, 14.00]);
    translate([12.523, -50.921, -1]) cube([16.000, 27.726, 14.00]);
  }
}

module half_rx() {
  difference() {
    union() {
      tray_rx();
      arm_rx();
    translate([212.805, -63.421, 0])
      cube([34.00, 14.500, 12.00]);
    }
    translate([198.805, -37.521, -1]) cube([28.000, 16.000, 14.00]);
    translate([198.805, 12.523, -1]) cube([28.000, 16.000, 14.00]);
  }
}


// ---------------------------------------------------------------- shelf
// Bolts to the four M4 points on the bar and carries both electronics
// boards behind the arrays.  Print flat.  214 x 96 mm.
module shelf() {
  difference() {
    union() {
      cube([214.00, 96.00, 5.00]);
      translate([31.000, 95.000, 0]) cube([28.0, 43.000, 5.00]);
      translate([161.000, 95.000, 0]) cube([28.0, 22.000, 5.00]);
    }
    translate([11.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([11.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([11.000, 85.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([11.000, 85.000, -1]) cylinder(d=3.40, h=7.00);
    translate([42.500, 28.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([42.500, 28.000, -1]) cylinder(d=3.40, h=7.00);
    translate([42.500, 68.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([42.500, 68.000, -1]) cylinder(d=3.40, h=7.00);
    translate([101.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([101.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([101.000, 85.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([101.000, 85.000, -1]) cylinder(d=3.40, h=7.00);
    translate([121.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([121.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([121.000, 69.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([121.000, 69.000, -1]) cylinder(d=3.40, h=7.00);
    translate([152.500, 24.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([152.500, 24.000, -1]) cylinder(d=3.40, h=7.00);
    translate([152.500, 56.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([152.500, 56.000, -1]) cylinder(d=3.40, h=7.00);
    translate([203.000, 11.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([203.000, 11.000, -1]) cylinder(d=3.40, h=7.00);
    translate([203.000, 69.000, -1]) cylinder(d=7.159, h=3.80, $fn=6);
    translate([203.000, 69.000, -1]) cylinder(d=3.40, h=7.00);
    translate([45.000, 131.000, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([67.000, 131.000, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([175.000, 110.000, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    translate([197.000, 110.000, -1]) cylinder(d=4.50, h=7.00, $fn=24);
    // lighten it: it only has to be flat and hold nine bolts
    for (i = [0 : 3]) for (j = [0 : 1])
      translate([24.00 + i * 46, 26.00 + j * 34, -1])
        cube([26, 22, 7.00]);
  }
}

if (part == "shelf") shelf();
else if (part == "transmit") half_tx();
else if (part == "receive") half_rx();
else {
  half_tx();
  half_rx();
  translate([-2.558, -183.921, -5.00])
    color("#4a6fa5") shelf();
  // the aluminium, and the boards sitting on it
  color("silver") translate([-45.921, -34.195, 5.00])
    cube([91.00, 67.00, 1.50]);
  color("silver") translate([215.805, -45.921, 5.00])
    cube([67.00, 91.00, 1.50]);
  color("green") translate([-35.921, -34.195,
    6.50])
    cube([71.342, 47.237, 0.76]);
  color("green") translate([215.805, -35.921,
    6.50])
    cube([47.237, 71.342, 0.76]);
}
