//============================================================================
// radar_b200_shim.v -- GENERATED by fpga/build/integrate_b200.py. Do not edit.
//
// Port-identical wrapper around radio_legacy.  It exists so that inserting the
// radar core into the b200 design is a one-token change to the stock sources
// instead of a patch that rots.
//
// When the radar is disabled the shim is transparent and the board is an
// ordinary B210.  When it is enabled, the receive path the radio packetises is
// the radar's output frame stream, one 32-bit word per sc16 sample, and the
// transmit path is driven by the chirp generated in the fabric.
//
// Generated against radio_legacy with 11 ports.
//============================================================================
`default_nettype none

module radar_b200_shim (
    input radio_clk,
    input radio_rst,
    input [31:0] rx,
    input rx_stb,
    output [31:0] tx,
    input tx_stb,
    output set_stb,
    output [7:0] set_addr,
    output [31:0] set_data,
    input [63:0] vita_time,
    output [63:0] debug
);

    //-- Radar core -------------------------------------------------------
    wire [31:0] radar_out_data;
    wire        radar_out_valid;
    wire        radar_enabled;
    wire [15:0] radar_tx_i, radar_tx_q;
    wire        radar_tx_valid;

    radar_top u_radar (
        .radio_clk   (radio_clk),
        .radio_rst   (radio_rst),
        .set_stb     (set_stb),
        .set_addr    (set_addr),
        .set_data    (set_data),
        // Two receive channels arrive interleaved on the b200 sample bus in
        // 2R2T mode; radar_top de-interleaves them internally using rx_stb.
        .rx_data     (rx),
        .rx_stb      (rx_stb),
        .tx_i        (radar_tx_i),
        .tx_q        (radar_tx_q),
        .tx_valid    (radar_tx_valid),
        .out_data    (radar_out_data),
        .out_valid   (radar_out_valid),
        .out_ready   (1'b1),
        .out_last    (),
        .enabled     (radar_enabled)
    );

    // Receive mux: the radio packetiser sees radar frames or raw IQ.
    wire [31:0] radio_rx_mux     = radar_enabled ? radar_out_data  : rx;
    wire        radio_rx_stb_mux = radar_enabled ? radar_out_valid : rx_stb;

    //-- The original radio, untouched ------------------------------------
    radio_legacy u_radio (
        .radio_clk(radio_clk),
        .radio_rst(radio_rst),
        .rx(radio_rx_mux),
        .rx_stb(radio_rx_stb_mux),
        .tx(tx),
        .tx_stb(tx_stb),
        .set_stb(set_stb),
        .set_addr(set_addr),
        .set_data(set_data),
        .vita_time(vita_time),
        .debug(debug)
    );

endmodule

`default_nettype wire
